version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - DB_CONNECTION=sqlsrv
      - DB_HOST=softinix.com
      - DB_PORT=1433
      - DB_DATABASE=EducaVirtual_DEV_180924
      - DB_USERNAME=Escalafon
      - DB_PASSWORD=lksd3498shbzlfh2ue
      - DB_TRUST_SERVER_CERTIFICATE=true
      - DB_ENCRYPT=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
